version: '3'
services:
        nginx:
                restart: always
                build: ./requirements/nginx/
                image: nginx
                volumes:
                        - /home/amine/data/wp-data:/www/wordpress
                ports:
                        - '443:443'
        wordpress:
                restart: always
                build: ./requirements/wordpress
                image: wordpress
                depends_on:
                        - nginx
                volumes:
                        - /home/amine/data/wp-data:/www/wordpress
                ports:
                        - '9000:9000'
