version: "3"
services:
        nginx:
                restart: always
                build: ./requirements/nginx/
                image: nginx
                depends_on:
                        - mariadb
                volumes:
                        - /home/amine/data/wp-data:/www/wordpress
                ports:
                        - "443:443"
                networks:
                        - mynetwork
                env_file:
                        - .env
        mariadb:
                restart: always
                build: ./requirements/mariadb/
                image: mariadb
                volumes:
                        - /home/amine/data/mar-data:/var/lib/mysql
                ports:
                        - "3306:3306"
                networks:
                        - mynetwork
                env_file:
                        - .env
        wordpress:
                env_file:
                        - .env
                restart: always
                build: ./requirements/wordpress
                image: wordpress
                depends_on:
                        - nginx
                volumes:
                        - /home/amine/data/wp-data:/www/wordpress
                        - /home/amine/data/mar-data:/var/lib/mysql
                ports:
                        - "9000:9000"
                networks:
                        - mynetwork
        redis:
                container_name: redis
                restart: always
                image: redis
                build: ./requirements/bonus/redis
                env_file:
                        - .env
                depends_on:
                        - wordpress
                volumes:
                        - /home/amine/data/wp-data:/www/wordpress
                ports:
                        - '6379:6379'
                networks:
                        - mynetwork
        adminer:
                image: adminer
                container_name: adminer
                restart: always
                build: ./requirements/bonus/adminer/
                ports:
                        - '8080:8080'
                depends_on:
                        - mariadb
                
                env_file:
                        - .env
                volumes:
                        - /home/amine/data/mar-data:/var/lib/mysql
                networks:
                        - mynetwork
        ftp:
                container_name: ftp
                image: ftp
                restart: always
                build: ./requirements/bonus/ftp/
                depends_on:
                        - wordpress
                env_file:
                        - .env
                volumes:
                        - /home/amine/data/wp-data:/home/ahaddad 
                ports:
                        - '21:21'
                        - '30000:30000'
                networks:
                        - mynetwork
        gitea:
                container_name: gitea
                image: gitea
                restart: always
                build: ./requirements/bonus/gitea/
                depends_on:
                        - mariadb
                env_file:
                        - .env
                volumes:
                        - /home/amine/data/mar-data:/var/lib/mysql
                ports:
                        - '22:22'
                        - '3000:3000'
                networks:
                        - mynetwork
        website:
                container_name: website
                image: website
                restart: always
                build: ./requirements/bonus/website/
                ports:
                        - '4040:4040'
                
                env_file:
                        - .env
                networks:
                        - mynetwork
networks:
        mynetwork:
