version: "3"
services:
        nginx:
                restart: always
                build: ./requirements/nginx/
                image: nginx
                depends_on:
                        - mariadb
                volumes:
                        - /home/amine/data/wp-data:/www/wordpress
                ports:
                        - "443:443"
                networks:
                        - mynetwork
                environment:
                        - .env
        mariadb:
                restart: always
                build: ./requirements/mariadb/
                image: mariadb
                volumes:
                        - /home/amine/data/mar-data:/var/lib/mysql
                ports:
                        - "3306:3306"
                networks:
                        - mynetwork
                environment:
                        - .env
        wordpress:
                environment:
                        - .env
                restart: always
                build: ./requirements/wordpress
                image: wordpress
                depends_on:
                        - nginx
                volumes:
                        - /home/amine/data/wp-data:/www/wordpress
                        - /home/amine/data/mar-data:/var/lib/mysql
                ports:
                        - "9000:9000"
                networks:
                        - mynetwork
        redis:
                container_name: redis
                restart: always
                image: redis
                build: ./requirements/bonus/redis
                depends_on:
                        - wordpress
                volumes:
                        - /home/amine/data/wp-data:/www/wordpress
                ports:
                        - '6379:6379'
                networks:
                        - mynetwork
        adminer:
                image: adminer
                container_name: adminer
                restart: always
                build: ./requirements/bonus/adminer/
                ports:
                        - '8080:8080'
                depends_on:
                        - mariadb
                volumes:
                        - /home/amine/data/mar-data:/var/lib/mysql
                networks:
                        - mynetwork
networks:
        mynetwork:
